apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: us-east-1

nodeGroups:
  - name: spot-ng
    privateNetworking: true
    minSize: 1
    maxSize: 10
    desiredCapacity: 1   
    instancesDistribution:
      instanceTypes: ["m5.large", "m5d.large", "m4.large","t3.large","t3a.large","m5a.large","t2.large"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotAllocationStrategy: "capacity-optimized"
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        albIngress: true
  - name: on-demand-ng
    privateNetworking: true
    minSize: 0
    maxSize: 10
    desiredCapacity: 0
    instancesDistribution:
      instanceTypes: ["m5.large", "m5d.large", "m4.large","t3.large","t3a.large","m5a.large","t2.large"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 100
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        albIngress: true
