---
apiVersion : v1
kind: PersistentVolumeClaim
metadata:
  name: ksqldb-extention
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2