apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-priority-expander
  namespace: kube-system
data:
  priorities: |-
    10: 
      - *on-demand*
    20: 
      - *spot-ng*

# 10 -> NAME-OF-THE-ASG
# 20 -> NAME-OF-THE-ASG